apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-simple-webapp
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: helm
    repoURL: https://github.com/Q29vbA/aws-webapp-manifests.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}